//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/2025 Testing Misc/Player/PC Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PCControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PCControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PC Controls"",
    ""maps"": [
        {
            ""name"": ""In Game Controls"",
            ""id"": ""beeb94d2-0944-450a-b5df-3619eb8e90fd"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""492b7b2c-90f5-4e03-a302-9b6e8f64bed0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""bbf1e9e4-2be6-444c-b5f9-bc90760df83c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9a67bc29-2f61-4456-be13-568e173575dd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65652e43-8a9a-4f4c-890f-cdb76e22c25e"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // In Game Controls
        m_InGameControls = asset.FindActionMap("In Game Controls", throwIfNotFound: true);
        m_InGameControls_Interact = m_InGameControls.FindAction("Interact", throwIfNotFound: true);
        m_InGameControls_Pause = m_InGameControls.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // In Game Controls
    private readonly InputActionMap m_InGameControls;
    private List<IInGameControlsActions> m_InGameControlsActionsCallbackInterfaces = new List<IInGameControlsActions>();
    private readonly InputAction m_InGameControls_Interact;
    private readonly InputAction m_InGameControls_Pause;
    public struct InGameControlsActions
    {
        private @PCControls m_Wrapper;
        public InGameControlsActions(@PCControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_InGameControls_Interact;
        public InputAction @Pause => m_Wrapper.m_InGameControls_Pause;
        public InputActionMap Get() { return m_Wrapper.m_InGameControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameControlsActions set) { return set.Get(); }
        public void AddCallbacks(IInGameControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameControlsActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IInGameControlsActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IInGameControlsActions instance)
        {
            if (m_Wrapper.m_InGameControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameControlsActions @InGameControls => new InGameControlsActions(this);
    public interface IInGameControlsActions
    {
        void OnInteract(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
