//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/2025 Testing Misc/Player/VR Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VRControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VRControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VR Controls"",
    ""maps"": [
        {
            ""name"": ""In Game Controls"",
            ""id"": ""a756c0c4-073b-4bc4-b19f-17678fc82d0d"",
            ""actions"": [
                {
                    ""name"": ""LeftHandToggle"",
                    ""type"": ""Button"",
                    ""id"": ""9ac03a3e-135d-433f-80a7-afdf28f77046"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ae43be19-f484-49b0-828b-5273c57ffeac"",
                    ""path"": ""<XRController>/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHandToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // In Game Controls
        m_InGameControls = asset.FindActionMap("In Game Controls", throwIfNotFound: true);
        m_InGameControls_LeftHandToggle = m_InGameControls.FindAction("LeftHandToggle", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // In Game Controls
    private readonly InputActionMap m_InGameControls;
    private List<IInGameControlsActions> m_InGameControlsActionsCallbackInterfaces = new List<IInGameControlsActions>();
    private readonly InputAction m_InGameControls_LeftHandToggle;
    public struct InGameControlsActions
    {
        private @VRControls m_Wrapper;
        public InGameControlsActions(@VRControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftHandToggle => m_Wrapper.m_InGameControls_LeftHandToggle;
        public InputActionMap Get() { return m_Wrapper.m_InGameControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameControlsActions set) { return set.Get(); }
        public void AddCallbacks(IInGameControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameControlsActionsCallbackInterfaces.Add(instance);
            @LeftHandToggle.started += instance.OnLeftHandToggle;
            @LeftHandToggle.performed += instance.OnLeftHandToggle;
            @LeftHandToggle.canceled += instance.OnLeftHandToggle;
        }

        private void UnregisterCallbacks(IInGameControlsActions instance)
        {
            @LeftHandToggle.started -= instance.OnLeftHandToggle;
            @LeftHandToggle.performed -= instance.OnLeftHandToggle;
            @LeftHandToggle.canceled -= instance.OnLeftHandToggle;
        }

        public void RemoveCallbacks(IInGameControlsActions instance)
        {
            if (m_Wrapper.m_InGameControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameControlsActions @InGameControls => new InGameControlsActions(this);
    public interface IInGameControlsActions
    {
        void OnLeftHandToggle(InputAction.CallbackContext context);
    }
}
